### ISSUE TITLE
While composing docker container got error

### ISSUE THREAD

**Issue by jerminal** [krystianity/keras-serving#1]
Error from logs:

`The command '/bin/sh -c cd serving && bazel build //tensorflow_serving/model_servers:tensorflow_model_server' returned a non-zero code: 1`

**Comment by krystianity** [comment]
Hi @jerminal, I will look into it.

**Comment by krystianity** [comment]
The build runs fine on my workstation.

I tried to build this image on docker hub and provide it as a downloadable layer; sadly the build process is canceled as it takes longer than 2 hours. https://hub.docker.com/r/krystianity/keras-serving/builds/bfqguf6ecwhukwhntqcdkab/

What are your specs? Operating system, Docker version? 
Are you simply executing the ./prepare.sh script?

**Comment by krystianity** [comment]
Hi @jerminal again, I have made a few adjustments - please just try to `git pull` and run `./prepare.sh` again, it should compile fine this time.

**Comment by jerminal** [comment]
Thanks, Great!

**Comment by jerminal** [comment]
Hello. Could you help me with changing it for image serving. Because I trained models, but can't integrate them in node-js server.
